version: '2'
services:
  rdb:
    image: rethinkdb
    ports:
      - "9090:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - ./nodes/rdb/data:/data

  api:
    build: nodes/api/
    environment:
      - PORT=$API_PORT
    ports:
      - $API_PORT

  links:
    build: nodes/links/
    environment:
      - PORT=$LINKS_PORT
    ports:
      - $LINKS_PORT
    links:
      - rdb

  metric:
    build: nodes/metrics/
    environment:
      - PORT=$METRIC_PORT
    ports:
      - $METRIC_PORT
    links:
      - rdb

  ui:
    build: 
      context: nodes/ui/
      args:
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT
    ports:
      - "$UI_PORT:$UI_PORT"

  lb1:
    image: dockercloud/haproxy
    ports:
      - "$API_PORT:80"
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lb2:
    image: dockercloud/haproxy
    ports:
      - "$LINKS_PORT:80"
    links:
      - links
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lb3:
    image: dockercloud/haproxy
    ports:
      - "$METRIC_PORT:80"
    links:
      - metric
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock